"""Add hashed_password column

Revision ID: 1cbb5ccc8506
Revises: c3fd089c6cd6
Create Date: 2025-04-15 01:54:23.025952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbb5ccc8506'
down_revision: Union[str, None] = 'c3fd089c6cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
